name: "Upload Coverage and Start Amplify Deployment"
description: "Upload coverage artifacts to S3 and trigger an Amplify deployment."
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS Access Key'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS Secret Key'
    required: true
  BUCKET_NAME:
    description: 'S3 Bucket Name'
    required: true
  AWS_DEFAULT_REGION:
    description: 'AWS Default Region'
    required: true
  BRANCH_NAME:
    description: 'Branch Name'
    required: true
  AMPLIFY_APP_ID:
    description: 'Amplify App ID'
    required: true
  AMPLIFY_HOST_URL:
    description: 'Amplify Host URL'
    required: true
  COVERAGE_SUBDIRECTORY:
    description: 'Subdirectory for coverage artifacts'
    required: false
    default: 'coverage'

runs:
  using: "composite"
  steps:
    - name: Upload coverage artifact to S3
      shell: bash
      run: |
        echo "Uploading coverage artifact to S3 under ${{ github.repository }}/${INPUT_BRANCH_NAME}/${{ github.run_id }}/${INPUT_COVERAGE_SUBDIRECTORY}/"
        aws s3 cp ${INPUT_COVERAGE_SUBDIRECTORY}/ s3://${INPUT_BUCKET_NAME}/artifacts/${{ github.repository }}/${INPUT_BRANCH_NAME}/${{ github.run_id }}/${INPUT_COVERAGE_SUBDIRECTORY}/ --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
        INPUT_BUCKET_NAME: ${{ inputs.BUCKET_NAME }}
        INPUT_BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
        INPUT_COVERAGE_SUBDIRECTORY: ${{ inputs.COVERAGE_SUBDIRECTORY || 'coverage' }}

    - name: Start Amplify deployment
      shell: bash
      run: |
        echo "Starting Amplify deployment..."
        aws amplify start-deployment \
          --app-id ${{ inputs.AMPLIFY_APP_ID }} \
          --branch-name main \
          --source-url s3://${{ inputs.BUCKET_NAME }}/ \
          --source-url-type BUCKET_PREFIX
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}

    - name: Append Coverage Report URL to Step Summary
      shell: bash
      run: |
        echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "${{ inputs.AMPLIFY_HOST_URL }}/artifacts/${{ github.repository }}/${{ inputs.BRANCH_NAME }}/${{ github.run_id }}/${INPUT_COVERAGE_SUBDIRECTORY}/" >> $GITHUB_STEP_SUMMARY
      env:
        INPUT_COVERAGE_SUBDIRECTORY: ${{ inputs.COVERAGE_SUBDIRECTORY || 'coverage' }}
